[package]
name = "happs"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "happs"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
happs_integrity = { workspace = true }
